### ISSUE TITLE
problem with default language in oc2.3.0.2

### ISSUE THREAD

**Issue by jasminejjj777** [opencart-russia/opencart-russia-language-2x#1]
hi , 
At first ,i'd like to thank you for your translation

Here is the issue... 

On "clean" oc site , i add russian language (in Locale tab from admin panel i add 
Locale : ru,ru_RU,ru_RU.UTF-8 
Code :ru-ru
Language Name:Russian
Sort-order:1
Enabled ) 
then ,from downloaded zip, i added ru-ru folder in admin/language/ru-ru  and catalog/language/ru-ru  accordingly.

ENGLISH IS THE DEFAULT LANGUAGE 

THE PROBLEM -- after installing russian language, my site in fronted(with cleaned sessions and cookies) shows russian language AS DEFAULT ,instead of showing ENGLISH. 
How to fix this ????

**Comment by opencart-russia** [comment]
Hi.
See \catalog\controller\startup\startup.php

and delete code 

```
			if (!$detect) { 
				// Try using language folder to detect the language
				foreach ($browser_languages as $browser_language) {
					if (array_key_exists(strtolower($browser_language), $languages)) {
						$detect = strtolower($browser_language);
						
						break;
					}
				}
			}
```

**Comment by opencart-russia** [comment]
and use translate from https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=16735&filter_category_id=2
or from
http://opencart-russia.ru/down.php?opencart2.3.0.2

**Comment by jasminejjj777** [comment]
Thank you so much ,it works!!!
By the way, will deleting that part from code cause new issues or errors ???
For what is this part of code responsible ???

**Comment by opencart-russia** [comment]
It's not a bug, it's incorrectly working piece of code. 
This part of code responsible for trying using language folder to detect the language using the language information from the browser

**Comment by jasminejjj777** [comment]
ok ,thank you  for your help and response!!!
